import type { Repository } from '../../../interfaces/repository';

export const repositoriesMock: Repository[] = [
  {
    id: '1',
    githubRepoId: 1018259548,
    name: 'portfolio',
    fullName: 'esteban-lt/portfolio',
    description: 'A modern Astro portfolio builded with TypeScript and Tailwind CSS',
    isActive: true,
    isPrivate: false,
    stars: 1247,
    forks: 89,
    issues: 12,
    pullRequests: 3,
    languaje: 'TypeScript',
  },
  {
    id: '2',
    githubRepoId: 123,
    name: 'api-gateway',
    fullName: 'esteban-lt/api-gateway',
    description: 'High-performance API gateway built with Node.js and Express',
    isActive: true,
    isPrivate: false,
    stars: 856,
    forks: 124,
    issues: 8,
    pullRequests: 5,
    languaje: 'JavaScript',
  },
  {
    id: '3',
    githubRepoId: 123,
    name: 'mobile-app',
    fullName: 'esteban-lt/mobile-app',
    description: 'Cross-platform mobile application using React Native',
    isActive: false,
    isPrivate: true,
    stars: 2103,
    forks: 245,
    issues: 23,
    pullRequests: 7,
    languaje: 'TypeScript',
  },
  {
    id: '4',
    githubRepoId: 123,
    name: 'design-system',
    fullName: 'esteban-lt/design-system',
    description: 'Comprehensive design system and component library',
    isActive: true,
    isPrivate: false,
    stars: 567,
    forks: 67,
    issues: 5,
    pullRequests: 2,
    languaje: 'TypeScript',
  },
];
